#!/usr/bin/env bash
# installs nginx on a remote server with it's configuration

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
