#!/usr/bin/env bash
# Nginx server redirecting to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://youtu.be/dQw4w9WgXcQ?si=Y9JkIcuV_W4qdpRz permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
