#!/usr/bin/env bash
# A script that displays the content of "/etc/passwd"
# and only displays Username, User ID and the Home directory path for the user

while IFS= read -r line;
do
	echo "$line" | cut -d ":" -f 1,3,6
done < "/etc/passwd"
